version: '3.7'
services:
  moodle:
    image: moodlehq/moodle-php-apache:8.2
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/html
    environment:
      - MOODLE_DOCKER_DBTYPE=mysqli
      - MOODLE_DOCKER_DBHOST=db
      - MOODLE_DOCKER_DBNAME=moodle
      - MOODLE_DOCKER_DBUSER=moodle
      - MOODLE_DOCKER_DBPASS=moodle
      - MOODLE_DOCKER_WWWROOT=http://localhost:8888
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    ports:
      - "3306:3306"
  php:
    image: php:8.2
    command: ["php", "-r", "echo 'zend.exception_ignore_args=On' > /usr/local/etc/php/conf.d/99-zend-exception-ignore-args.ini"]